# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d17e2f5f34bbdd1f39affd71b60675c757d0e1477674720a1a06270f23df912b6e222be1f751edba16b1923f33f10118700e962ddbf8082f82ffc68aab4525e5

test:
  secret_key_base: 170817c9564d60bb80d38dafd02ae2fdf863c3e7dea2e74eb061e61267d952b5a2938613d58b11ec0f2bcd75c789dcb7c86df85df21dcbca3cf605cd11f943c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
